---
- name: Ensure Cockpit plugins are installed
  become: true
  tags:
    - cockpit
    - cockpit_plugins
  ansible.builtin.dnf:
    name: "{{ cockpit_plugins }}"
    state: "{{ cockpit_pkg_state }}"
    update_cache: true
  when: ansible_os_family == "RedHat"
